export enum SiteAction {
  Read = 'read',
  ReadUserEvents = 'readUserEvents',
  UpdateGeneral = 'updateGeneral',
  UpdateSwapFees = 'updateSwapFees',
  UpdateMarketplaceFees = 'updateMarketplaceFees',
  UpdateDomain = 'updateDomain',
  UpdateOwnership = 'updateOwnership',
  UpdateSocialMedia = 'updateSocialMedia',
  UpdateTheme = 'updateTheme',
  UpdatePages = 'updatePages',
  UpdateMenu = 'updateMenu',
  UpdateFooterMenu = 'updateFooterMenu',
  UpdateSeo = 'updateSeo',
  UpdateAnalytics = 'updateAnalytics',
  UpdatesCollections = 'updateCollections',
  UpdateTokens = 'updateTokens',
}
